[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "airport champion chapter scorpion demise team blast speed catalog scrap weasel economy half butter exact list argue tomorrow symptom always range cereal owner coral"
